//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyanetNamazVakti.Api.Core.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrayerTime.Core.Globalization.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erişim Engellendi.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aksiyon Adı.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemler.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm hakları saklıdır..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahsil Edilen.
        /// </summary>
        public static string AmountCharged {
            get {
                return ResourceManager.GetString("AmountCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru.
        /// </summary>
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyurular.
        /// </summary>
        public static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylı.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkindi.
        /// </summary>
        public static string Asr {
            get {
                return ResourceManager.GetString("Asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomik Gün Doğumu.
        /// </summary>
        public static string AstronomicalSunrise {
            get {
                return ResourceManager.GetString("AstronomicalSunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomik Gün Batımı.
        /// </summary>
        public static string AstronomicalSunset {
            get {
                return ResourceManager.GetString("AstronomicalSunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barkod.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanım Hakkı.
        /// </summary>
        public static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string CategoryManagement {
            get {
                return ResourceManager.GetString("CategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İller.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrarı.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik Türü.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolör Adı.
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçeler.
        /// </summary>
        public static string Counties {
            get {
                return ResourceManager.GetString("Counties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülke.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapak Resmi.
        /// </summary>
        public static string CoverImage {
            get {
                return ResourceManager.GetString("CoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulma Tarihi.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturan.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye.
        /// </summary>
        public static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Limiti.
        /// </summary>
        public static string CustomerLimit {
            get {
                return ResourceManager.GetString("CustomerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri İsmi.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteriler.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı Türü.
        /// </summary>
        public static string DatabaseType {
            get {
                return ResourceManager.GetString("DatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yılın Günü.
        /// </summary>
        public static string DayOfYear {
            get {
                return ResourceManager.GetString("DayOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslimat Süresi (Gün).
        /// </summary>
        public static string DeliveryDay {
            get {
                return ResourceManager.GetString("DeliveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslimat Zamanı.
        /// </summary>
        public static string DeliveryTime {
            get {
                return ResourceManager.GetString("DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğle.
        /// </summary>
        public static string Dhuhr {
            get {
                return ResourceManager.GetString("Dhuhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüntülenme Sırası.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabe&apos;ye Uzaklık.
        /// </summary>
        public static string DistanceToKaaba {
            get {
                return ResourceManager.GetString("DistanceToKaaba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurban Bayramı.
        /// </summary>
        public static string EidAlAdha {
            get {
                return ResourceManager.GetString("EidAlAdha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurban Bayramı Namazı Tarihi.
        /// </summary>
        public static string EidAlAdhaDate {
            get {
                return ResourceManager.GetString("EidAlAdhaDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurban Bayramı Namazı Saati.
        /// </summary>
        public static string EidAlAdhaTime {
            get {
                return ResourceManager.GetString("EidAlAdhaTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramazan Bayramı.
        /// </summary>
        public static string EidAlFitr {
            get {
                return ResourceManager.GetString("EidAlFitr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramazan Bayramı Namazı Tarihi.
        /// </summary>
        public static string EidAlFitrDate {
            get {
                return ResourceManager.GetString("EidAlFitrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramazan Bayramı Namazı Saati.
        /// </summary>
        public static string EidAlFitrTime {
            get {
                return ResourceManager.GetString("EidAlFitrTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Zamanı.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinebilir mi?.
        /// </summary>
        public static string Erasable {
            get {
                return ResourceManager.GetString("Erasable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmsak.
        /// </summary>
        public static string Fajr {
            get {
                return ResourceManager.GetString("Fajr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrele.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finans.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finansal İşlemler.
        /// </summary>
        public static string Finances {
            get {
                return ResourceManager.GetString("Finances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yabancı Ad.
        /// </summary>
        public static string ForeignName {
            get {
                return ResourceManager.GetString("ForeignName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Yüz.
        /// </summary>
        public static string FrontSide {
            get {
                return ResourceManager.GetString("FrontSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coğrafi Kıble Açısı.
        /// </summary>
        public static string GeographicQiblaAngle {
            get {
                return ResourceManager.GetString("GeographicQiblaAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşterilere gözat.
        /// </summary>
        public static string GotoCustomers {
            get {
                return ResourceManager.GetString("GotoCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finansal işlemlere gözat.
        /// </summary>
        public static string GotoFinances {
            get {
                return ResourceManager.GetString("GotoFinances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişlere gözat.
        /// </summary>
        public static string GotoOrders {
            get {
                return ResourceManager.GetString("GotoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miladi Tarih.
        /// </summary>
        public static string GregorianDate {
            get {
                return ResourceManager.GetString("GregorianDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hadis.
        /// </summary>
        public static string Hadith {
            get {
                return ResourceManager.GetString("Hadith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hadis Numarası.
        /// </summary>
        public static string HadithSource {
            get {
                return ResourceManager.GetString("HadithSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hicri Tarih.
        /// </summary>
        public static string HijriDate {
            get {
                return ResourceManager.GetString("HijriDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim Tarihi Gelenler Otomatik Olarak Güncellensin.
        /// </summary>
        public static string IDeliveriesAutomatic {
            get {
                return ResourceManager.GetString("IDeliveriesAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik No.
        /// </summary>
        public static string IdentityCode {
            get {
                return ResourceManager.GetString("IdentityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolamı Unuttum.
        /// </summary>
        public static string IForgotMyPassword {
            get {
                return ResourceManager.GetString("IForgotMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Dosyası.
        /// </summary>
        public static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylandı mı?.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatsı.
        /// </summary>
        public static string Isha {
            get {
                return ResourceManager.GetString("Isha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Gönderim İzni Veriyor mu?.
        /// </summary>
        public static string IsSmsSending {
            get {
                return ResourceManager.GetString("IsSmsSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Tipi.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Tipleri.
        /// </summary>
        public static string JobTypes {
            get {
                return ResourceManager.GetString("JobTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahtar.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string LanguageManagement {
            get {
                return ResourceManager.GetString("LanguageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştirilme Tarihi.
        /// </summary>
        public static string LastModificationTime {
            get {
                return ResourceManager.GetString("LastModificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştiren.
        /// </summary>
        public static string LastModifier {
            get {
                return ResourceManager.GetString("LastModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Sipariş.
        /// </summary>
        public static string LastOrder {
            get {
                return ResourceManager.GetString("LastOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Siparişin Durumu.
        /// </summary>
        public static string LastOrderStatus {
            get {
                return ResourceManager.GetString("LastOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlem.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seviye.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listele.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boylam.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akşam.
        /// </summary>
        public static string Maghrib {
            get {
                return ResourceManager.GetString("Maghrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçü Birimi.
        /// </summary>
        public static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçü Birimleri.
        /// </summary>
        public static string Measures {
            get {
                return ResourceManager.GetString("Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuManagement {
            get {
                return ResourceManager.GetString("MenuManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Ücret.
        /// </summary>
        public static string MonthlyPrice {
            get {
                return ResourceManager.GetString("MonthlyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cami.
        /// </summary>
        public static string Mosque {
            get {
                return ResourceManager.GetString("Mosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Parola.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonra.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaysız.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre Grubu.
        /// </summary>
        public static string ParameterGroup {
            get {
                return ResourceManager.GetString("ParameterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre Grubu.
        /// </summary>
        public static string ParameterGroupManagement {
            get {
                return ResourceManager.GetString("ParameterGroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre Grupları.
        /// </summary>
        public static string ParameterGroups {
            get {
                return ResourceManager.GetString("ParameterGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre.
        /// </summary>
        public static string ParameterManagement {
            get {
                return ResourceManager.GetString("ParameterManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametreler.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alacak.
        /// </summary>
        public static string PendingReceipts {
            get {
                return ResourceManager.GetString("PendingReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periyod.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki.
        /// </summary>
        public static string PermissionManagement {
            get {
                return ResourceManager.GetString("PermissionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkiler.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numarası.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaka.
        /// </summary>
        public static string Plate {
            get {
                return ResourceManager.GetString("Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dua.
        /// </summary>
        public static string Pray {
            get {
                return ResourceManager.GetString("Pray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dua Kaynak.
        /// </summary>
        public static string PraySource {
            get {
                return ResourceManager.GetString("PraySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önce.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölge.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölgeler.
        /// </summary>
        public static string Provinces {
            get {
                return ResourceManager.GetString("Provinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayın Başlangıç Zamanı.
        /// </summary>
        public static string PublishBeginTime {
            get {
                return ResourceManager.GetString("PublishBeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayın Bitiş Zamanı.
        /// </summary>
        public static string PublishEndTime {
            get {
                return ResourceManager.GetString("PublishEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıble Açısı.
        /// </summary>
        public static string QiblaAngle {
            get {
                return ResourceManager.GetString("QiblaAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıble Saati.
        /// </summary>
        public static string QiblaTime {
            get {
                return ResourceManager.GetString("QiblaTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kota.
        /// </summary>
        public static string Quota {
            get {
                return ResourceManager.GetString("Quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt olmak İstiyorum.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan Kullanım Hakkı.
        /// </summary>
        public static string RemainingUse {
            get {
                return ResourceManager.GetString("RemainingUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndPoint (Action) Adı.
        /// </summary>
        public static string ResultName {
            get {
                return ResourceManager.GetString("ResultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahsilat.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahsil Eden.
        /// </summary>
        public static string Revenuer {
            get {
                return ResourceManager.GetString("Revenuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahsil Eden.
        /// </summary>
        public static string RevenuerName {
            get {
                return ResourceManager.GetString("RevenuerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahsilatlar.
        /// </summary>
        public static string Revenues {
            get {
                return ResourceManager.GetString("Revenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahsilat Zamanı.
        /// </summary>
        public static string RevenueTime {
            get {
                return ResourceManager.GetString("RevenueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string RoleManagement {
            get {
                return ResourceManager.GetString("RoleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satır Numarası.
        /// </summary>
        public static string RowId {
            get {
                return ResourceManager.GetString("RowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlanan Teslimat Zamanı.
        /// </summary>
        public static string ScheduledDeliveryTime {
            get {
                return ResourceManager.GetString("ScheduledDeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aranan.
        /// </summary>
        public static string Searched {
            get {
                return ResourceManager.GetString("Searched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama İfadesi.
        /// </summary>
        public static string SearchTerm {
            get {
                return ResourceManager.GetString("SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Seçiniz---.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıra No.
        /// </summary>
        public static string SequenceNumber {
            get {
                return ResourceManager.GetString("SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayın Şekli.
        /// </summary>
        public static string ShapeMoon {
            get {
                return ResourceManager.GetString("ShapeMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfada Gösterilecek Kayıt Sayısı.
        /// </summary>
        public static string ShowingInPage {
            get {
                return ResourceManager.GetString("ShowingInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaynak.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlama Zamanı.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyalet / Şehir.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoklar.
        /// </summary>
        public static string Stocks {
            get {
                return ResourceManager.GetString("Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özet.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün Doğumu.
        /// </summary>
        public static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simge.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Adı.
        /// </summary>
        public static string TenantName {
            get {
                return ResourceManager.GetString("TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmalar.
        /// </summary>
        public static string Tenants {
            get {
                return ResourceManager.GetString("Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Türü.
        /// </summary>
        public static string TenantType {
            get {
                return ResourceManager.GetString("TenantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Türleri.
        /// </summary>
        public static string TenantTypes {
            get {
                return ResourceManager.GetString("TenantTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Kayıt Sayısı.
        /// </summary>
        public static string TotalItemsCount {
            get {
                return ResourceManager.GetString("TotalItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Sipariş Sayısı.
        /// </summary>
        public static string TotalOrderNumber {
            get {
                return ResourceManager.GetString("TotalOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar.
        /// </summary>
        public static string TotalSum {
            get {
                return ResourceManager.GetString("TotalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Tarihi.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemi Yapan.
        /// </summary>
        public static string Transactioner {
            get {
                return ResourceManager.GetString("Transactioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Zamanı.
        /// </summary>
        public static string TransactionTime {
            get {
                return ResourceManager.GetString("TransactionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Fiyat.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellenme Zamanı.
        /// </summary>
        public static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanılan.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Bilgisi.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Limiti.
        /// </summary>
        public static string UserLimit {
            get {
                return ResourceManager.GetString("UserLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değer.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araç.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araçlar.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayet.
        /// </summary>
        public static string Verse {
            get {
                return ResourceManager.GetString("Verse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayet Numarası.
        /// </summary>
        public static string VerseSource {
            get {
                return ResourceManager.GetString("VerseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sürüm.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıllık Ücret.
        /// </summary>
        public static string YearlyPrice {
            get {
                return ResourceManager.GetString("YearlyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
